### ISSUE TITLE
VSCode Issues

### ISSUE THREAD

**Issue by bhk11** [upb-lea/control-block-diagram#4]
I tested the control-block-diagramm with Visual Studio Code and have 2 issues when I run the examples.

1. doc.show() doesn't work:
![image](https://user-images.githubusercontent.com/95769661/176189072-c2e1e95d-b0c6-479a-b5ca-c7fbd39ef305.png)
Adding a "import sys" to control_diagram.py solves the error_message, but no block-diagramm is displayed.

2. If I run the cell a second time, the saving window of doc.save() isn't opening again and the cell doesn't terminate.

**Comment by samidiamond** [comment]
in line 33 you forgot the text you should write text instead of txt

**Comment by samidiamond** [comment]
in line 33 you should write 'text' instead of 'tex'

**Comment by bhk11** [comment]
@samidiamond no, 'tex' is correct. That line works as expected. A latex file of the figure and also a pdf file are generated.

**Comment by fbook98** [comment]
I have added the import of the sys module.

**Comment by wallscheid** [comment]
Is that fixed here @fbook98 and @bhk11 ? Can we close the issue?

**Comment by bhk11** [comment]
Yes, I close the issue.
