### ISSUE TITLE
PyPi package?

### ISSUE THREAD

**Issue by matte1** [upb-lea/control-block-diagram#6]
Any chance you plan on making this available too pip? I'm unfortunately stuck in a place where I can only use python packages that are available for pip due to sand boxing. Looks like a cool project!

**Comment by wallscheid** [comment]
@wkirgsn : could you take care of that?

**Comment by wkirgsn** [comment]
will do

**Comment by wallscheid** [comment]
great, thanks!

**Comment by matte1** [comment]
Thank you much!!
